### ISSUE TITLE
Make A header component

### ISSUE THREAD

**Issue by OysteinKoder** [OysteinKoder/kodehode-web-page#2]
Use styled components. 
should contain header, navbar, logo. 
see figma file for reference. 

Make new branch called : 
feat/header

from main: 
git checkout -b feat/header

https://www.figma.com/proto/36gZt0YkWI7BgNwLCtHycK/kodehode-side?node-id=1%3A99

**Comment by knutcode** [comment]
Added as new branch
[kodehode-web-page/tree/feat/header](https://github.com/OysteinKoder/kodehode-web-page/tree/feat/header)
